# Robust PocketSDR FX3 Makefile - Resolving Standard C Symbols

# --- Toolchain Paths ---
FX3FWROOT ?= /opt/cypress/fx3sdk/cyfx3sdk
CROSS_COMPILE ?= /opt/cypress/fx3sdk/arm-2013.11/bin/arm-none-eabi-

CC      = $(CROSS_COMPILE)gcc
AS      = $(CROSS_COMPILE)gcc
LD      = $(CROSS_COMPILE)gcc
ELF2IMG = $(FX3FWROOT)/util/elf2img/elf2img

# --- SDK & Toolchain Library Paths ---
FX3SDK_INC  = -I$(FX3FWROOT)/fw_lib/1_3_5/inc
FX3SDK_INC += -I$(FX3FWROOT)/firmware/u3p_firmware/inc
FX3_LIB_DIR = $(FX3FWROOT)/firmware/u3p_firmware/lib/fx3_release

# Locate the toolchain's internal libc.a folder
TOOLCHAIN_LIB = /opt/cypress/fx3sdk/arm-2013.11/arm-none-eabi/lib

# --- Compiler Flags ---
CFLAGS  = -Wall -O2 -g -mcpu=arm926ej-s -marm -std=gnu99 -fno-builtin -fshort-wchar
CFLAGS += -D__CYU3P_TX__
CFLAGS += -I. $(FX3SDK_INC)

ASFLAGS = -Wall -c -g -mcpu=arm926ej-s -marm

# --- Linker Flags ---
LDFLAGS  = -T $(FX3FWROOT)/fw_build/fx3_fw/fx3.ld 
LDFLAGS += -nostdlib -L$(TOOLCHAIN_LIB) -Wl,-Map,pocket_fw_v3.map

# Circular group that includes ALL your code objects and SDK libraries together
LIBS  = -Wl,--start-group
LIBS += $(OBJECTS)
LIBS += $(FX3_LIB_DIR)/cyfxapi.a
LIBS += $(FX3_LIB_DIR)/cyu3lpp.a
LIBS += $(FX3_LIB_DIR)/cyu3threadx.a
LIBS += -lc
LIBS += -lgcc
LIBS += -Wl,--end-group

# --- Target Files ---
MODULE = pocket_fw_v3
SOURCE = pocket_fw_v3.c pocket_usb_dscr.c cyfxtx.c
ASM_SOURCE = cyfx_gcc_startup.S

OBJECTS = $(SOURCE:%.c=%.o) $(ASM_SOURCE:%.S=%.o)


# --- Build Rules ---
all: $(MODULE).img

$(MODULE).img: $(MODULE).elf
	$(ELF2IMG) -i $< -o $@

$(MODULE).elf: $(OBJECTS)
	$(LD) $(LDFLAGS) $(LIBS) -o $@

cyfxtx.c:
	cp $(FX3FWROOT)/fw_build/fx3_fw/cyfxtx.c .

cyfx_gcc_startup.S:
	cp $(FX3FWROOT)/fw_build/fx3_fw/cyfx_gcc_startup.S .

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.S
	$(AS) $(ASFLAGS) -c $< -o $@

clean:
	rm -f *.o *.elf *.map *.img cyfxtx.c cyfx_startup.S cyfx_gcc_startup.S

.PHONY: all clean

